// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Orchestratum.Database;

#nullable disable

namespace Orchestratum.Example.Migrations
{
    [DbContext(typeof(OrchestratorDbContext))]
    partial class OrchestratorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Orchestratum.Database.OrchestratorCommandDbo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompleteAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("complete_at");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_type");

                    b.Property<string>("Executor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("executor");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<bool>("IsFailed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_failed");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("boolean")
                        .HasColumnName("is_running");

                    b.Property<int>("RetriesLeft")
                        .HasColumnType("integer")
                        .HasColumnName("retries_left");

                    b.Property<DateTimeOffset?>("RunExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_expires_at");

                    b.Property<TimeSpan>("Timeout")
                        .HasColumnType("interval")
                        .HasColumnName("timeout");

                    b.HasKey("Id");

                    b.HasIndex("IsCompleted");

                    b.HasIndex("IsFailed");

                    b.HasIndex("IsRunning");

                    b.ToTable("orchestrator_commands");
                });
#pragma warning restore 612, 618
        }
    }
}
