// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Orchestratum.Database;

#nullable disable

namespace Orchestratum.Example.Migrations
{
    [DbContext(typeof(OrchDbContext))]
    partial class OrchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Orchestratum.Database.OrchCommandDbo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CanceledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("canceled_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("Input")
                        .HasColumnType("text")
                        .HasColumnName("input");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_canceled");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<bool>("IsFailed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_failed");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("boolean")
                        .HasColumnName("is_running");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Output")
                        .HasColumnType("text")
                        .HasColumnName("output");

                    b.Property<int>("RetriesLeft")
                        .HasColumnType("integer")
                        .HasColumnName("retries_left");

                    b.Property<DateTimeOffset?>("RunExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_expires_at");

                    b.Property<DateTimeOffset?>("RunningAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("running_at");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target");

                    b.Property<TimeSpan>("Timeout")
                        .HasColumnType("interval")
                        .HasColumnName("timeout");

                    b.HasKey("Id");

                    b.HasIndex("IsCompleted");

                    b.HasIndex("IsFailed");

                    b.HasIndex("IsRunning");

                    b.HasIndex("Target");

                    b.ToTable("ORCH_commands", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
